apiVersion: ec2.services.k8s.aws/v1alpha1
kind: VPCEndpoint
metadata:
  name: $VPC_ENDPOINT_NAME #Change the VPC Endpoint Name
spec:
  serviceName: $SERVICE_NAME #Change the Service Name
  vpcID: $VPC_ID #Change the VPC ID
  routeTableIDs:
  - $ROUTE_TABLE_ID #Change the Route Table ID
  securityGroupIDs:
  - $SECURITY_GROUP_ID #Change the Security Group ID
  subnetIDs:
  - $SUBNET_ID #Change the Subnet ID
  tagSpecifications:
  - resourceType: "vpcendpoint"
    tags:
    - key: $VPC_ENDPOINT_TAG_KEY #Change the tag key
      value: $VPC_ENDPOINT_TAG_VALUE #Change the tag value